# Generated by Django 4.2.7 on 2023-12-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
